version: "3"
services: 
    web:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.prod
            args: 
                - TESTENV=hello
        ports:
            - "8080:80"
        # image : ws-thunk 
        # container_name: thunk-container   
        environment: 
                - REACT_APP_NAME=wassim
                - CHOKIDAR_USEPOLLING=true
        env_file: 
                - ./.env
