version: "3"
services: 
    dev:
        # stdin_open: true
        # tty: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${CLIENT_PORT}:3000"
        image : ws-thunk 
        container_name: thunk-container   
        volumes: 
            - ./src:/app/src
        environment: 
                - REACT_APP_NAME=wassim
                - CHOKIDAR_USEPOLLING=true
        env_file: 
                - ./.env
